# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 732b832e5bcc402d891c8d3129498f63098528d478221bdb4922a17711bc6c562bee4db57ccba98bf510ff643989a6b76b3176564af6513b5c5c7e163b5b8d9c

test:
  secret_key_base: 2b0453037f4eeb332e8354274ed00892b52a00a650f0505b7532ea84acd6dd5a6ca2b9a3599ecd1bbd4eb1a088ec99945ab04bab1b805f4f5170d546c60a689c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
