# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2abe09f8060d3a3a52d3e04168defa44a120ac4d6a244a85a045f126482517d43c8f916c65d005f7fe111c59b743e5673127d827f3fabbae72169a220defbe33

test:
  secret_key_base: cdb4321dadad3c0a8b3459dde53060f93279afd590ece768234cccc5d95628352b10b637711af7193d5b78738aeb9db39eea0bb04a1b456c1a904cb51f5c7e77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
